/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Databases */
        get: operations["list_databases_api_databases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/database/{db_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Database */
        get: operations["get_database_api_database__db_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_api_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media_api_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{account_id}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Media */
        get: operations["serve_media_api_media__account_id___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Storage */
        get: operations["list_storage_api_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export Data */
        get: operations["get_export_data_api_export_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Log Events */
        get: operations["list_log_events_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ghosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ghosts */
        get: operations["list_ghosts_api_ghosts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forensics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Forensics */
        get: operations["list_forensics_api_forensics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Chat */
        Chat: {
            /** Id */
            id: string;
            /** All Peer Ids */
            all_peer_ids: string[];
            /** Name */
            name: string;
            /**
             * Username
             * @default
             */
            username: string;
            /** Type */
            type: string;
            /** Has Fts */
            has_fts: boolean;
            /** Message Count */
            message_count: number;
            /** Last Message */
            last_message?: number | string | null;
            /** Databases */
            databases: string[];
        };
        /** DatabaseDetail */
        DatabaseDetail: {
            /** Decrypted */
            decrypted: boolean;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /** Peers */
            peers: {
                [key: string]: unknown;
            }[];
            /** Conversations */
            conversations: {
                [key: string]: unknown;
            }[];
            /** Media Catalog */
            media_catalog: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** DatabaseSummary */
        DatabaseSummary: {
            /** Name */
            name: string;
            /** Decrypted */
            decrypted: boolean;
            /** Message Count */
            message_count: number;
            /** Tables */
            tables: string[];
        };
        /** ExportData */
        ExportData: {
            /**
             * Accounts
             * @default []
             */
            accounts: unknown[];
            /**
             * Databases
             * @default {}
             */
            databases: {
                [key: string]: unknown;
            };
            /**
             * Media Files
             * @default []
             */
            media_files: unknown[];
            /**
             * Total Media
             * @default 0
             */
            total_media: number;
            /**
             * Backup Size
             * @default
             */
            backup_size: string;
        };
        /** ForensicEntry */
        ForensicEntry: {
            /** File Id */
            file_id: number;
            /**
             * Filenames
             * @default []
             */
            filenames: string[];
            /** Size Bytes */
            size_bytes?: number | null;
            /**
             * On Disk
             * @default false
             */
            on_disk: boolean;
            /**
             * Tombstone
             * @default false
             */
            tombstone: boolean;
            /**
             * Sources
             * @default []
             */
            sources: string[];
            log_event?: components["schemas"]["ForensicLog"] | null;
            message?: components["schemas"]["ForensicMessage"] | null;
            /**
             * Account
             * @default
             */
            account: string;
        };
        /** ForensicLog */
        ForensicLog: {
            /** Dcid */
            dcId?: number | null;
            /** Accesshash */
            accessHash?: number | null;
            /** Size */
            size?: number | null;
            /** Keyfingerprint */
            keyFingerprint?: number | null;
            /** Chatid */
            chatId?: number | null;
            /** Date */
            date?: number | null;
            /**
             * Source File
             * @default
             */
            source_file: string;
            /**
             * Source Line
             * @default 0
             */
            source_line: number;
        } & {
            [key: string]: unknown;
        };
        /** ForensicMessage */
        ForensicMessage: {
            /**
             * Account
             * @default
             */
            account: string;
            /** Peer Id */
            peer_id?: number | null;
            /** Peer Name */
            peer_name?: string | null;
            /** Timestamp */
            timestamp?: number | null;
            /** Date */
            date?: string | null;
            /** Outgoing */
            outgoing?: boolean | null;
        };
        /** ForensicPage */
        ForensicPage: {
            /** Items */
            items: components["schemas"]["ForensicEntry"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /**
         * GhostEntry
         * @description One message that diverged between two parsed_data snapshots.
         */
        GhostEntry: {
            /** Peer Id */
            peer_id?: number | null;
            /** Peer Name */
            peer_name?: string | null;
            /** Timestamp */
            timestamp?: number | null;
            /** Date */
            date?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Media
             * @default []
             */
            media: {
                [key: string]: unknown;
            }[];
            /** Outgoing */
            outgoing?: boolean | null;
            /**
             * Account
             * @default
             */
            account: string;
        } & {
            [key: string]: unknown;
        };
        /** GhostPage */
        GhostPage: {
            /** Items */
            items: components["schemas"]["GhostEntry"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Kind */
            kind: string;
            /** Previous Snapshot */
            previous_snapshot?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LogEvent
         * @description One forensic event extracted from a Telegram macOS debug log.
         *
         *     Shape mirrors `tool.log_parser`'s record format. `data` is event-specific
         *     so we leave it flexible. `in_db` + `db_match` are populated only for
         *     `encrypted_message` events; `account` is added at API serialization time.
         */
        LogEvent: {
            /** Event */
            event: string;
            /**
             * Source File
             * @default
             */
            source_file: string;
            /**
             * Source Line
             * @default 0
             */
            source_line: number;
            /**
             * Log Timestamp
             * @default
             */
            log_timestamp: string;
            /**
             * Data
             * @default {}
             */
            data: {
                [key: string]: unknown;
            };
            /** In Db */
            in_db?: boolean | null;
            /** Db Match */
            db_match?: {
                [key: string]: unknown;
            } | null;
            /**
             * Account
             * @default
             */
            account: string;
        } & {
            [key: string]: unknown;
        };
        /** LogEventPage */
        LogEventPage: {
            /** Events */
            events: components["schemas"]["LogEvent"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** MediaItem */
        MediaItem: {
            /**
             * Filename
             * @default
             */
            filename: string;
            /**
             * Mime Type
             * @default
             */
            mime_type: string;
            /**
             * Media Type
             * @default
             */
            media_type: string;
            /**
             * Account
             * @default
             */
            account: string;
            /** Linked Message */
            linked_message?: {
                [key: string]: unknown;
            } | null;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Size */
            size?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Duration */
            duration?: number | null;
        };
        /** MediaPage */
        MediaPage: {
            /** Media */
            media: components["schemas"]["MediaItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** Message */
        Message: {
            /**
             * Text
             * @default
             */
            text: string;
            /** Peer Id */
            peer_id?: number | string | null;
            /** Timestamp */
            timestamp?: number | string | null;
            /** Outgoing */
            outgoing?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** MessagesPage */
        MessagesPage: {
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** Stats */
        Stats: {
            /** Total Databases */
            total_databases: number;
            /** Decrypted Databases */
            decrypted_databases: number;
            /** Total Messages */
            total_messages: number;
            /** Total Chats */
            total_chats: number;
            /** Databases */
            databases: {
                [key: string]: components["schemas"]["StatsDb"];
            };
        };
        /** StatsDb */
        StatsDb: {
            /** Decrypted */
            decrypted: boolean;
            /** Message Count */
            message_count: number;
            /** Tables */
            tables: number;
        };
        /** StorageEntry */
        StorageEntry: {
            /** Filename */
            filename: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * On Disk
             * @default true
             */
            on_disk: boolean;
            /** Absolute Path */
            absolute_path?: string | null;
            /**
             * Account
             * @default
             */
            account: string;
        };
        /** StoragePage */
        StoragePage: {
            /** Items */
            items: components["schemas"]["StorageEntry"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /** User */
        User: {
            /** Id */
            id: number | string;
            /** Name */
            name: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /** Database */
            database: string;
        };
        /** UsersPage */
        UsersPage: {
            /** Users */
            users: components["schemas"]["User"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_databases_api_databases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseSummary"][];
                };
            };
        };
    };
    get_database_api_database__db_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                search?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_chats_get: {
        parameters: {
            query?: {
                search?: string;
                type?: string;
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_messages_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                database?: string;
                search?: string;
                peer_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_api_media_get: {
        parameters: {
            query?: {
                search?: string;
                type?: string;
                account?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_media_api_media__account_id___filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_storage_api_storage_get: {
        parameters: {
            query?: {
                tombstone_only?: boolean;
                source?: string;
                search?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoragePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    get_export_data_api_export_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportData"];
                };
            };
        };
    };
    list_log_events_api_logs_get: {
        parameters: {
            query?: {
                /** @description Filter to one event type (e.g. encrypted_message) */
                event_type?: string;
                /** @description Only encrypted_message events with no matching t7 row */
                ghost_only?: boolean;
                /** @description Filter encrypted_message / pending_removed by peer_id (comma-separated) */
                peer_id?: string;
                /** @description Restrict to one account-{id} */
                account?: string;
                /** @description Substring match against the event's source_file + data dict */
                search?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ghosts_api_ghosts_get: {
        parameters: {
            query?: {
                account?: string;
                kind?: string;
                search?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GhostPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_forensics_api_forensics_get: {
        parameters: {
            query?: {
                tombstone_only?: boolean;
                with_message?: boolean;
                with_log?: boolean;
                account?: string;
                search?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForensicPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
